//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NXP3_GetPublicationDetails.Baseline25ServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InfoShareFault", Namespace="http://sdl.com/trisoft/2012/06/WebServices/Contracts/Faults/API25/")]
    [System.SerializableAttribute()]
    public partial class InfoShareFault : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long InfoShareErrorNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OriginField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string XMLDetailField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long InfoShareErrorNumber {
            get {
                return this.InfoShareErrorNumberField;
            }
            set {
                if ((this.InfoShareErrorNumberField.Equals(value) != true)) {
                    this.InfoShareErrorNumberField = value;
                    this.RaisePropertyChanged("InfoShareErrorNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Origin {
            get {
                return this.OriginField;
            }
            set {
                if ((object.ReferenceEquals(this.OriginField, value) != true)) {
                    this.OriginField = value;
                    this.RaisePropertyChanged("Origin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string XMLDetail {
            get {
                return this.XMLDetailField;
            }
            set {
                if ((object.ReferenceEquals(this.XMLDetailField, value) != true)) {
                    this.XMLDetailField = value;
                    this.RaisePropertyChanged("XMLDetail");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ActivityFilter", Namespace="http://sdl.com/trisoft/2012/06/WebServices/Contracts/Enumerations/API25/")]
    public enum ActivityFilter : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        None = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Active = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Inactive = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaselineAutoCompleteMode", Namespace="http://sdl.com/trisoft/2012/06/WebServices/Contracts/Enumerations/API25/")]
    public enum BaselineAutoCompleteMode : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ISHFirstVersion = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ISHLatestReleased = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ISHLatestAvailable = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://sdl.com/trisoft/2012/06/WebServices/Services/API25/", ConfigurationName="Baseline25ServiceReference.Baseline")]
    public interface Baseline {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sdl.com/trisoft/2012/06/WebServices/Services/API25/Baseline/RetrieveMetada" +
            "ta", ReplyAction="http://sdl.com/trisoft/2012/06/WebServices/Services/API25/Baseline/RetrieveMetada" +
            "taResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(NXP3_GetPublicationDetails.Baseline25ServiceReference.InfoShareFault), Action="http://sdl.com/trisoft/2012/06/WebServices/Services/API25/Baseline/RetrieveMetada" +
            "taInfoShareFault", Name="InfoShareFault", Namespace="http://sdl.com/trisoft/2012/06/WebServices/Contracts/Faults/API25/")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="xmlObjectList")]
        string RetrieveMetadata(string[] baselineIds, string xmlMetadataFilter, string xmlRequestedMetadata);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sdl.com/trisoft/2012/06/WebServices/Services/API25/Baseline/RetrieveMetada" +
            "ta2", ReplyAction="http://sdl.com/trisoft/2012/06/WebServices/Services/API25/Baseline/RetrieveMetada" +
            "ta2Response")]
        [System.ServiceModel.FaultContractAttribute(typeof(NXP3_GetPublicationDetails.Baseline25ServiceReference.InfoShareFault), Action="http://sdl.com/trisoft/2012/06/WebServices/Services/API25/Baseline/RetrieveMetada" +
            "ta2InfoShareFault", Name="InfoShareFault", Namespace="http://sdl.com/trisoft/2012/06/WebServices/Contracts/Faults/API25/")]
        string RetrieveMetadata2(string[] baselineIds, NXP3_GetPublicationDetails.Baseline25ServiceReference.ActivityFilter activityFilter, string xmlMetadataFilter, string xmlRequestedMetadata);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sdl.com/trisoft/2012/06/WebServices/Services/API25/Baseline/Find", ReplyAction="http://sdl.com/trisoft/2012/06/WebServices/Services/API25/Baseline/FindResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(NXP3_GetPublicationDetails.Baseline25ServiceReference.InfoShareFault), Action="http://sdl.com/trisoft/2012/06/WebServices/Services/API25/Baseline/FindInfoShareF" +
            "ault", Name="InfoShareFault", Namespace="http://sdl.com/trisoft/2012/06/WebServices/Contracts/Faults/API25/")]
        string Find(NXP3_GetPublicationDetails.Baseline25ServiceReference.ActivityFilter activityFilter, string xmlMetadataFilter, string xmlRequestedMetadata);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sdl.com/trisoft/2012/06/WebServices/Services/API25/Baseline/GetMetadata", ReplyAction="http://sdl.com/trisoft/2012/06/WebServices/Services/API25/Baseline/GetMetadataRes" +
            "ponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(NXP3_GetPublicationDetails.Baseline25ServiceReference.InfoShareFault), Action="http://sdl.com/trisoft/2012/06/WebServices/Services/API25/Baseline/GetMetadataInf" +
            "oShareFault", Name="InfoShareFault", Namespace="http://sdl.com/trisoft/2012/06/WebServices/Contracts/Faults/API25/")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="xmlObjectList")]
        string GetMetadata(string baselineId, string xmlRequestedMetadata);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sdl.com/trisoft/2012/06/WebServices/Services/API25/Baseline/GetList", ReplyAction="http://sdl.com/trisoft/2012/06/WebServices/Services/API25/Baseline/GetListRespons" +
            "e")]
        [System.ServiceModel.FaultContractAttribute(typeof(NXP3_GetPublicationDetails.Baseline25ServiceReference.InfoShareFault), Action="http://sdl.com/trisoft/2012/06/WebServices/Services/API25/Baseline/GetListInfoSha" +
            "reFault", Name="InfoShareFault", Namespace="http://sdl.com/trisoft/2012/06/WebServices/Contracts/Faults/API25/")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="xmlObjectList")]
        string GetList(string xmlMetadataFilter, string xmlRequestedMetadata);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sdl.com/trisoft/2012/06/WebServices/Services/API25/Baseline/GetBaselineNam" +
            "e", ReplyAction="http://sdl.com/trisoft/2012/06/WebServices/Services/API25/Baseline/GetBaselineNam" +
            "eResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(NXP3_GetPublicationDetails.Baseline25ServiceReference.InfoShareFault), Action="http://sdl.com/trisoft/2012/06/WebServices/Services/API25/Baseline/GetBaselineNam" +
            "eInfoShareFault", Name="InfoShareFault", Namespace="http://sdl.com/trisoft/2012/06/WebServices/Contracts/Faults/API25/")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="returnValue")]
        string GetBaselineName(string baselineId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sdl.com/trisoft/2012/06/WebServices/Services/API25/Baseline/GetBaselineId", ReplyAction="http://sdl.com/trisoft/2012/06/WebServices/Services/API25/Baseline/GetBaselineIdR" +
            "esponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(NXP3_GetPublicationDetails.Baseline25ServiceReference.InfoShareFault), Action="http://sdl.com/trisoft/2012/06/WebServices/Services/API25/Baseline/GetBaselineIdI" +
            "nfoShareFault", Name="InfoShareFault", Namespace="http://sdl.com/trisoft/2012/06/WebServices/Contracts/Faults/API25/")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="returnValue")]
        string GetBaselineId(string baselineName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sdl.com/trisoft/2012/06/WebServices/Services/API25/Baseline/Containing", ReplyAction="http://sdl.com/trisoft/2012/06/WebServices/Services/API25/Baseline/ContainingResp" +
            "onse")]
        [System.ServiceModel.FaultContractAttribute(typeof(NXP3_GetPublicationDetails.Baseline25ServiceReference.InfoShareFault), Action="http://sdl.com/trisoft/2012/06/WebServices/Services/API25/Baseline/ContainingInfo" +
            "ShareFault", Name="InfoShareFault", Namespace="http://sdl.com/trisoft/2012/06/WebServices/Contracts/Faults/API25/")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="xmlObjectList")]
        string Containing(string logicalId, string versionNumber, string xmlRequestedMetadata);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sdl.com/trisoft/2012/06/WebServices/Services/API25/Baseline/GetBaseline", ReplyAction="http://sdl.com/trisoft/2012/06/WebServices/Services/API25/Baseline/GetBaselineRes" +
            "ponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(NXP3_GetPublicationDetails.Baseline25ServiceReference.InfoShareFault), Action="http://sdl.com/trisoft/2012/06/WebServices/Services/API25/Baseline/GetBaselineInf" +
            "oShareFault", Name="InfoShareFault", Namespace="http://sdl.com/trisoft/2012/06/WebServices/Contracts/Faults/API25/")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="xmlObjectList")]
        string GetBaseline(out string xmlBaseline, string baselineId, string xmlRequestedMetadata);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sdl.com/trisoft/2012/06/WebServices/Services/API25/Baseline/GetReport", ReplyAction="http://sdl.com/trisoft/2012/06/WebServices/Services/API25/Baseline/GetReportRespo" +
            "nse")]
        [System.ServiceModel.FaultContractAttribute(typeof(NXP3_GetPublicationDetails.Baseline25ServiceReference.InfoShareFault), Action="http://sdl.com/trisoft/2012/06/WebServices/Services/API25/Baseline/GetReportInfoS" +
            "hareFault", Name="InfoShareFault", Namespace="http://sdl.com/trisoft/2012/06/WebServices/Contracts/Faults/API25/")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="xmlBaselineReport")]
        string GetReport(string baselineId, string[] startResourceLogicalIds, string[] languages, string[] illustrationLanguages, string[] resourceLanguages, string[] resolutions);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sdl.com/trisoft/2012/06/WebServices/Services/API25/Baseline/ExpandBaseline" +
            "", ReplyAction="http://sdl.com/trisoft/2012/06/WebServices/Services/API25/Baseline/ExpandBaseline" +
            "Response")]
        [System.ServiceModel.FaultContractAttribute(typeof(NXP3_GetPublicationDetails.Baseline25ServiceReference.InfoShareFault), Action="http://sdl.com/trisoft/2012/06/WebServices/Services/API25/Baseline/ExpandBaseline" +
            "InfoShareFault", Name="InfoShareFault", Namespace="http://sdl.com/trisoft/2012/06/WebServices/Contracts/Faults/API25/")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="xmlBaselineReport")]
        string ExpandBaseline(string baselineId, string[] startLogicalIds, string[] startResourceLogicalIds, string[] languages, string[] illustrationLanguages, string[] resourceLanguages, string[] resolutions);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sdl.com/trisoft/2012/06/WebServices/Services/API25/Baseline/ExpandReport", ReplyAction="http://sdl.com/trisoft/2012/06/WebServices/Services/API25/Baseline/ExpandReportRe" +
            "sponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(NXP3_GetPublicationDetails.Baseline25ServiceReference.InfoShareFault), Action="http://sdl.com/trisoft/2012/06/WebServices/Services/API25/Baseline/ExpandReportIn" +
            "foShareFault", Name="InfoShareFault", Namespace="http://sdl.com/trisoft/2012/06/WebServices/Contracts/Faults/API25/")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="outXmlBaselineReport")]
        string ExpandReport(string xmlBaselineReport, string[] startLogicalIds, string[] startResourceLogicalIds, string[] languages, string[] illustrationLanguages, string[] resourceLanguages, string[] resolutions);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sdl.com/trisoft/2012/06/WebServices/Services/API25/Baseline/CompleteBaseli" +
            "neByMode", ReplyAction="http://sdl.com/trisoft/2012/06/WebServices/Services/API25/Baseline/CompleteBaseli" +
            "neByModeResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(NXP3_GetPublicationDetails.Baseline25ServiceReference.InfoShareFault), Action="http://sdl.com/trisoft/2012/06/WebServices/Services/API25/Baseline/CompleteBaseli" +
            "neByModeInfoShareFault", Name="InfoShareFault", Namespace="http://sdl.com/trisoft/2012/06/WebServices/Contracts/Faults/API25/")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="xmlBaselineReport")]
        string CompleteBaselineByMode(string baselineId, NXP3_GetPublicationDetails.Baseline25ServiceReference.BaselineAutoCompleteMode autoCompleteMode, string[] startLogicalIds, string[] startResourceLogicalIds, string[] languages, string[] illustrationLanguages, string[] resourceLanguages, string[] resolutions);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sdl.com/trisoft/2012/06/WebServices/Services/API25/Baseline/CompleteReport" +
            "ByMode", ReplyAction="http://sdl.com/trisoft/2012/06/WebServices/Services/API25/Baseline/CompleteReport" +
            "ByModeResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(NXP3_GetPublicationDetails.Baseline25ServiceReference.InfoShareFault), Action="http://sdl.com/trisoft/2012/06/WebServices/Services/API25/Baseline/CompleteReport" +
            "ByModeInfoShareFault", Name="InfoShareFault", Namespace="http://sdl.com/trisoft/2012/06/WebServices/Contracts/Faults/API25/")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="outXmlBaselineReport")]
        string CompleteReportByMode(string xmlBaselineReport, NXP3_GetPublicationDetails.Baseline25ServiceReference.BaselineAutoCompleteMode autoCompleteMode, string[] startLogicalIds, string[] startResourceLogicalIds, string[] languages, string[] illustrationLanguages, string[] resourceLanguages, string[] resolutions);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sdl.com/trisoft/2012/06/WebServices/Services/API25/Baseline/CompleteBaseli" +
            "neByCandidateAndMode", ReplyAction="http://sdl.com/trisoft/2012/06/WebServices/Services/API25/Baseline/CompleteBaseli" +
            "neByCandidateAndModeResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(NXP3_GetPublicationDetails.Baseline25ServiceReference.InfoShareFault), Action="http://sdl.com/trisoft/2012/06/WebServices/Services/API25/Baseline/CompleteBaseli" +
            "neByCandidateAndModeInfoShareFault", Name="InfoShareFault", Namespace="http://sdl.com/trisoft/2012/06/WebServices/Contracts/Faults/API25/")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="outXmlBaselineReport")]
        string CompleteBaselineByCandidateAndMode(string baselineId, string extendBaselineId, NXP3_GetPublicationDetails.Baseline25ServiceReference.BaselineAutoCompleteMode autoCompleteMode, string[] startLogicalIds, string[] startResourceLogicalIds, string[] languages, string[] illustrationLanguages, string[] resourceLanguages, string[] resolutions);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sdl.com/trisoft/2012/06/WebServices/Services/API25/Baseline/CompleteReport" +
            "ByCandidateAndMode", ReplyAction="http://sdl.com/trisoft/2012/06/WebServices/Services/API25/Baseline/CompleteReport" +
            "ByCandidateAndModeResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(NXP3_GetPublicationDetails.Baseline25ServiceReference.InfoShareFault), Action="http://sdl.com/trisoft/2012/06/WebServices/Services/API25/Baseline/CompleteReport" +
            "ByCandidateAndModeInfoShareFault", Name="InfoShareFault", Namespace="http://sdl.com/trisoft/2012/06/WebServices/Contracts/Faults/API25/")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="outXmlBaselineReport")]
        string CompleteReportByCandidateAndMode(string xmlBaselineReport, string extendBaselineId, NXP3_GetPublicationDetails.Baseline25ServiceReference.BaselineAutoCompleteMode autoCompleteMode, string[] startLogicalIds, string[] startResourceLogicalIds, string[] languages, string[] illustrationLanguages, string[] resourceLanguages, string[] resolutions);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sdl.com/trisoft/2012/06/WebServices/Services/API25/Baseline/ExtendReportBy" +
            "Baseline", ReplyAction="http://sdl.com/trisoft/2012/06/WebServices/Services/API25/Baseline/ExtendReportBy" +
            "BaselineResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(NXP3_GetPublicationDetails.Baseline25ServiceReference.InfoShareFault), Action="http://sdl.com/trisoft/2012/06/WebServices/Services/API25/Baseline/ExtendReportBy" +
            "BaselineInfoShareFault", Name="InfoShareFault", Namespace="http://sdl.com/trisoft/2012/06/WebServices/Contracts/Faults/API25/")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="outXmlBaselineReport")]
        string ExtendReportByBaseline(string xmlBaselineReport, string extendBaselineId, string[] startLogicalIds, string[] startResourceLogicalIds, string[] languages, string[] illustrationLanguages, string[] resourceLanguages, string[] resolutions);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sdl.com/trisoft/2012/06/WebServices/Services/API25/Baseline/ExtendReportBy" +
            "Candidate", ReplyAction="http://sdl.com/trisoft/2012/06/WebServices/Services/API25/Baseline/ExtendReportBy" +
            "CandidateResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(NXP3_GetPublicationDetails.Baseline25ServiceReference.InfoShareFault), Action="http://sdl.com/trisoft/2012/06/WebServices/Services/API25/Baseline/ExtendReportBy" +
            "CandidateInfoShareFault", Name="InfoShareFault", Namespace="http://sdl.com/trisoft/2012/06/WebServices/Contracts/Faults/API25/")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="outXmlBaselineReport")]
        string ExtendReportByCandidate(string xmlBaselineReport, string extendBaselineId, string[] startLogicalIds, string[] startResourceLogicalIds, string[] languages, string[] illustrationLanguages, string[] resourceLanguages, string[] resolutions);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sdl.com/trisoft/2012/06/WebServices/Services/API25/Baseline/Create", ReplyAction="http://sdl.com/trisoft/2012/06/WebServices/Services/API25/Baseline/CreateResponse" +
            "")]
        [System.ServiceModel.FaultContractAttribute(typeof(NXP3_GetPublicationDetails.Baseline25ServiceReference.InfoShareFault), Action="http://sdl.com/trisoft/2012/06/WebServices/Services/API25/Baseline/CreateInfoShar" +
            "eFault", Name="InfoShareFault", Namespace="http://sdl.com/trisoft/2012/06/WebServices/Contracts/Faults/API25/")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="returnValue")]
        string Create(string baselineName, string userGroup);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sdl.com/trisoft/2012/06/WebServices/Services/API25/Baseline/Delete", ReplyAction="http://sdl.com/trisoft/2012/06/WebServices/Services/API25/Baseline/DeleteResponse" +
            "")]
        [System.ServiceModel.FaultContractAttribute(typeof(NXP3_GetPublicationDetails.Baseline25ServiceReference.InfoShareFault), Action="http://sdl.com/trisoft/2012/06/WebServices/Services/API25/Baseline/DeleteInfoShar" +
            "eFault", Name="InfoShareFault", Namespace="http://sdl.com/trisoft/2012/06/WebServices/Contracts/Faults/API25/")]
        void Delete(string baselineId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sdl.com/trisoft/2012/06/WebServices/Services/API25/Baseline/Update", ReplyAction="http://sdl.com/trisoft/2012/06/WebServices/Services/API25/Baseline/UpdateResponse" +
            "")]
        [System.ServiceModel.FaultContractAttribute(typeof(NXP3_GetPublicationDetails.Baseline25ServiceReference.InfoShareFault), Action="http://sdl.com/trisoft/2012/06/WebServices/Services/API25/Baseline/UpdateInfoShar" +
            "eFault", Name="InfoShareFault", Namespace="http://sdl.com/trisoft/2012/06/WebServices/Contracts/Faults/API25/")]
        void Update(string baselineId, string xmlChanges);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sdl.com/trisoft/2012/06/WebServices/Services/API25/Baseline/SetMetadata", ReplyAction="http://sdl.com/trisoft/2012/06/WebServices/Services/API25/Baseline/SetMetadataRes" +
            "ponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(NXP3_GetPublicationDetails.Baseline25ServiceReference.InfoShareFault), Action="http://sdl.com/trisoft/2012/06/WebServices/Services/API25/Baseline/SetMetadataInf" +
            "oShareFault", Name="InfoShareFault", Namespace="http://sdl.com/trisoft/2012/06/WebServices/Contracts/Faults/API25/")]
        void SetMetadata(string baselineId, string xmlMetadata);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sdl.com/trisoft/2012/06/WebServices/Services/API25/Baseline/Freeze", ReplyAction="http://sdl.com/trisoft/2012/06/WebServices/Services/API25/Baseline/FreezeResponse" +
            "")]
        [System.ServiceModel.FaultContractAttribute(typeof(NXP3_GetPublicationDetails.Baseline25ServiceReference.InfoShareFault), Action="http://sdl.com/trisoft/2012/06/WebServices/Services/API25/Baseline/FreezeInfoShar" +
            "eFault", Name="InfoShareFault", Namespace="http://sdl.com/trisoft/2012/06/WebServices/Contracts/Faults/API25/")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="returnValue")]
        bool Freeze(out string xmlBaselineFreezeReport, string baselineId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sdl.com/trisoft/2012/06/WebServices/Services/API25/Baseline/CanBeFrozen", ReplyAction="http://sdl.com/trisoft/2012/06/WebServices/Services/API25/Baseline/CanBeFrozenRes" +
            "ponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(NXP3_GetPublicationDetails.Baseline25ServiceReference.InfoShareFault), Action="http://sdl.com/trisoft/2012/06/WebServices/Services/API25/Baseline/CanBeFrozenInf" +
            "oShareFault", Name="InfoShareFault", Namespace="http://sdl.com/trisoft/2012/06/WebServices/Contracts/Faults/API25/")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="returnValue")]
        bool CanBeFrozen(out string xmlBaselineFreezeReport, string baselineId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sdl.com/trisoft/2012/06/WebServices/Services/API25/Baseline/CleanUp", ReplyAction="http://sdl.com/trisoft/2012/06/WebServices/Services/API25/Baseline/CleanUpRespons" +
            "e")]
        [System.ServiceModel.FaultContractAttribute(typeof(NXP3_GetPublicationDetails.Baseline25ServiceReference.InfoShareFault), Action="http://sdl.com/trisoft/2012/06/WebServices/Services/API25/Baseline/CleanUpInfoSha" +
            "reFault", Name="InfoShareFault", Namespace="http://sdl.com/trisoft/2012/06/WebServices/Contracts/Faults/API25/")]
        void CleanUp(string baselineId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sdl.com/trisoft/2012/06/WebServices/Services/API25/Baseline/Copy", ReplyAction="http://sdl.com/trisoft/2012/06/WebServices/Services/API25/Baseline/CopyResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(NXP3_GetPublicationDetails.Baseline25ServiceReference.InfoShareFault), Action="http://sdl.com/trisoft/2012/06/WebServices/Services/API25/Baseline/CopyInfoShareF" +
            "ault", Name="InfoShareFault", Namespace="http://sdl.com/trisoft/2012/06/WebServices/Contracts/Faults/API25/")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="returnValue")]
        string Copy(string baselineName, string userGroup, string sourceBaselineId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface BaselineChannel : NXP3_GetPublicationDetails.Baseline25ServiceReference.Baseline, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BaselineClient : System.ServiceModel.ClientBase<NXP3_GetPublicationDetails.Baseline25ServiceReference.Baseline>, NXP3_GetPublicationDetails.Baseline25ServiceReference.Baseline {
        
        public BaselineClient() {
        }
        
        public BaselineClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BaselineClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BaselineClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BaselineClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string RetrieveMetadata(string[] baselineIds, string xmlMetadataFilter, string xmlRequestedMetadata) {
            return base.Channel.RetrieveMetadata(baselineIds, xmlMetadataFilter, xmlRequestedMetadata);
        }
        
        public string RetrieveMetadata2(string[] baselineIds, NXP3_GetPublicationDetails.Baseline25ServiceReference.ActivityFilter activityFilter, string xmlMetadataFilter, string xmlRequestedMetadata) {
            return base.Channel.RetrieveMetadata2(baselineIds, activityFilter, xmlMetadataFilter, xmlRequestedMetadata);
        }
        
        public string Find(NXP3_GetPublicationDetails.Baseline25ServiceReference.ActivityFilter activityFilter, string xmlMetadataFilter, string xmlRequestedMetadata) {
            return base.Channel.Find(activityFilter, xmlMetadataFilter, xmlRequestedMetadata);
        }
        
        public string GetMetadata(string baselineId, string xmlRequestedMetadata) {
            return base.Channel.GetMetadata(baselineId, xmlRequestedMetadata);
        }
        
        public string GetList(string xmlMetadataFilter, string xmlRequestedMetadata) {
            return base.Channel.GetList(xmlMetadataFilter, xmlRequestedMetadata);
        }
        
        public string GetBaselineName(string baselineId) {
            return base.Channel.GetBaselineName(baselineId);
        }
        
        public string GetBaselineId(string baselineName) {
            return base.Channel.GetBaselineId(baselineName);
        }
        
        public string Containing(string logicalId, string versionNumber, string xmlRequestedMetadata) {
            return base.Channel.Containing(logicalId, versionNumber, xmlRequestedMetadata);
        }
        
        public string GetBaseline(out string xmlBaseline, string baselineId, string xmlRequestedMetadata) {
            return base.Channel.GetBaseline(out xmlBaseline, baselineId, xmlRequestedMetadata);
        }
        
        public string GetReport(string baselineId, string[] startResourceLogicalIds, string[] languages, string[] illustrationLanguages, string[] resourceLanguages, string[] resolutions) {
            return base.Channel.GetReport(baselineId, startResourceLogicalIds, languages, illustrationLanguages, resourceLanguages, resolutions);
        }
        
        public string ExpandBaseline(string baselineId, string[] startLogicalIds, string[] startResourceLogicalIds, string[] languages, string[] illustrationLanguages, string[] resourceLanguages, string[] resolutions) {
            return base.Channel.ExpandBaseline(baselineId, startLogicalIds, startResourceLogicalIds, languages, illustrationLanguages, resourceLanguages, resolutions);
        }
        
        public string ExpandReport(string xmlBaselineReport, string[] startLogicalIds, string[] startResourceLogicalIds, string[] languages, string[] illustrationLanguages, string[] resourceLanguages, string[] resolutions) {
            return base.Channel.ExpandReport(xmlBaselineReport, startLogicalIds, startResourceLogicalIds, languages, illustrationLanguages, resourceLanguages, resolutions);
        }
        
        public string CompleteBaselineByMode(string baselineId, NXP3_GetPublicationDetails.Baseline25ServiceReference.BaselineAutoCompleteMode autoCompleteMode, string[] startLogicalIds, string[] startResourceLogicalIds, string[] languages, string[] illustrationLanguages, string[] resourceLanguages, string[] resolutions) {
            return base.Channel.CompleteBaselineByMode(baselineId, autoCompleteMode, startLogicalIds, startResourceLogicalIds, languages, illustrationLanguages, resourceLanguages, resolutions);
        }
        
        public string CompleteReportByMode(string xmlBaselineReport, NXP3_GetPublicationDetails.Baseline25ServiceReference.BaselineAutoCompleteMode autoCompleteMode, string[] startLogicalIds, string[] startResourceLogicalIds, string[] languages, string[] illustrationLanguages, string[] resourceLanguages, string[] resolutions) {
            return base.Channel.CompleteReportByMode(xmlBaselineReport, autoCompleteMode, startLogicalIds, startResourceLogicalIds, languages, illustrationLanguages, resourceLanguages, resolutions);
        }
        
        public string CompleteBaselineByCandidateAndMode(string baselineId, string extendBaselineId, NXP3_GetPublicationDetails.Baseline25ServiceReference.BaselineAutoCompleteMode autoCompleteMode, string[] startLogicalIds, string[] startResourceLogicalIds, string[] languages, string[] illustrationLanguages, string[] resourceLanguages, string[] resolutions) {
            return base.Channel.CompleteBaselineByCandidateAndMode(baselineId, extendBaselineId, autoCompleteMode, startLogicalIds, startResourceLogicalIds, languages, illustrationLanguages, resourceLanguages, resolutions);
        }
        
        public string CompleteReportByCandidateAndMode(string xmlBaselineReport, string extendBaselineId, NXP3_GetPublicationDetails.Baseline25ServiceReference.BaselineAutoCompleteMode autoCompleteMode, string[] startLogicalIds, string[] startResourceLogicalIds, string[] languages, string[] illustrationLanguages, string[] resourceLanguages, string[] resolutions) {
            return base.Channel.CompleteReportByCandidateAndMode(xmlBaselineReport, extendBaselineId, autoCompleteMode, startLogicalIds, startResourceLogicalIds, languages, illustrationLanguages, resourceLanguages, resolutions);
        }
        
        public string ExtendReportByBaseline(string xmlBaselineReport, string extendBaselineId, string[] startLogicalIds, string[] startResourceLogicalIds, string[] languages, string[] illustrationLanguages, string[] resourceLanguages, string[] resolutions) {
            return base.Channel.ExtendReportByBaseline(xmlBaselineReport, extendBaselineId, startLogicalIds, startResourceLogicalIds, languages, illustrationLanguages, resourceLanguages, resolutions);
        }
        
        public string ExtendReportByCandidate(string xmlBaselineReport, string extendBaselineId, string[] startLogicalIds, string[] startResourceLogicalIds, string[] languages, string[] illustrationLanguages, string[] resourceLanguages, string[] resolutions) {
            return base.Channel.ExtendReportByCandidate(xmlBaselineReport, extendBaselineId, startLogicalIds, startResourceLogicalIds, languages, illustrationLanguages, resourceLanguages, resolutions);
        }
        
        public string Create(string baselineName, string userGroup) {
            return base.Channel.Create(baselineName, userGroup);
        }
        
        public void Delete(string baselineId) {
            base.Channel.Delete(baselineId);
        }
        
        public void Update(string baselineId, string xmlChanges) {
            base.Channel.Update(baselineId, xmlChanges);
        }
        
        public void SetMetadata(string baselineId, string xmlMetadata) {
            base.Channel.SetMetadata(baselineId, xmlMetadata);
        }
        
        public bool Freeze(out string xmlBaselineFreezeReport, string baselineId) {
            return base.Channel.Freeze(out xmlBaselineFreezeReport, baselineId);
        }
        
        public bool CanBeFrozen(out string xmlBaselineFreezeReport, string baselineId) {
            return base.Channel.CanBeFrozen(out xmlBaselineFreezeReport, baselineId);
        }
        
        public void CleanUp(string baselineId) {
            base.Channel.CleanUp(baselineId);
        }
        
        public string Copy(string baselineName, string userGroup, string sourceBaselineId) {
            return base.Channel.Copy(baselineName, userGroup, sourceBaselineId);
        }
    }
}
